# Generated by Django 4.1.6 on 2023-02-03 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='is_liked',
        ),
    ]
